### ISSUE TITLE
How will this app be useful for the average user?

### ISSUE THREAD

**Issue by Bubenchuk** [DexterDreeeam/Spear#1]
After configuring the client, on the phone, and the server, on the computer, will I be able to use the IP address specified on the server side, on the phone?

**Comment by DexterDreeeam** [comment]
Sorry, I missed this important part. Client Token should be  "110.110.110.110:22333" currently.
"110.110.110.110" is your server ip.
22333 is default server deploy config if you don't change anything.
no security authentication is applied yet.

**Comment by DexterDreeeam** [comment]
Update and close
